### ISSUE TITLE
Update to latest AuthorID

### ISSUE THREAD

**Issue by ghost** [zhangweis/AuthorIdentity#1]
Hi Zhang., 

Great work on this integration!

We mean 1 small change to AUTHOR ID to remove the Field Offset and Field Count:
https://github.com/BitcoinFiles/AUTHOR_IDENTITY_PROTOCOL#protocol

Please update to the latest.  This was a last minute breaking change -- but it simplifies the protocol greatly and it's still early.

We've updated the unit tests and fully updated at https://github.com/BitcoinFiles/bitcoinfiles-sdk as well.

Please let me know if I can be of further assistance.

From here on the protocol is now *locked down*.

Thank you,

**Comment by zhangweis** [comment]
Hi Attila,

I've updated the part to reflect the protocol change about removing field offset and field count.

Thanks for the update.

btw, will it be possible to have a simplified version signature so that I can leave field indexes empty to say I signed for all the fields before me?

**Comment by ghost** [comment]
That's a very good question cc @zhangweis 

Perhaps we can assume that all of the fields preceding it are signed if the offsets are omitted.  Is that what you mean?

That seems like a useful convention to have... I'm going to ask others in Atlantis about this idea. Seems good!

**Comment by zhangweis** [comment]
Yes, exactly what I meant. In this way, I can simply attach signature
without listing field indexes one by one.
